version: "3.1"

networks:
  app-tier:
    driver: bridge

services:

  app:
    build: .
    ports:
    - "8080:8080"
    extra_hosts:
      - 172.21.0.1
    depends_on:
      - rabbit


  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
    - 5672:5672
    - 15672:15672
    environment:
     RABBITMQ_DEFAULT_USER: root
     RABBITMQ_DEFAULT_PASS: 123456
    networks:
       - app-tier
    extra_hosts:
      - 172.21.0.1